entryPoints:
  web:
    address: ":5000"

providers:
  file:
    filename: "/etc/traefik/dynamic.yml"
    watch: true

api:
  dashboard: true
  insecure: true   # disable in production

log:
  level: INFO