# SERVER
server.port=${PORT:8040}
# APP
app.image.path=/app/data/img
# SECURITY
app.auth.issuer=${APP_OAUTH_ISSUER}
app.auth.client-id=${APP_OAUTH_CLIENT_ID:chronos-admin-ui}
app.auth.principle-attribute=
app.auth.admin-role=