services:

  chronos-hds:
    image: maven:3.9.6-eclipse-temurin-17-alpine
    container_name: chronos-hds
    working_dir: /app/chronos-historical-data-service
    command: mvn spring-boot:run
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
      - ./dev/exampledata/img:/app/data/img:ro
    depends_on:
      - chronos-hds-db
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev-security,test-data,debug
      APP_GDP_HOST: chronos-hds-db
      APP_GDB_USERNAME: neo4j
      APP_GDB_PASSWORD: password

  chronos-hds-db:
    container_name: chronos-hds-db
    image: neo4j:5.26.14-community-bullseye
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
    #    Activate for persistent local testdata:
    #    volumes:
    #      - "./dev/chronos-postgres-data:/var/lib/postgresql/data"
    #      - "./dev/chronos-neo4j-data:/data"

  chronos-sds:
    image: maven:3.9.6-eclipse-temurin-17-alpine
    container_name: chronos-sds
    working_dir: /app/chronos-schema-definition-service
    command: mvn spring-boot:run
    ports:
      - "8090:8090"
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    depends_on:
      - chronos-sds-db
    environment:
      SPRING_PROFILES_ACTIVE: dev-security,test-data,debug
      APP_DB_HOST: chronos-sds-db
      APP_DB_USER: sds-db-user
      APP_DB_PASSWORD: sds-db-password

  chronos-sds-db:
    image: postgres:18.1-alpine3.23
    container_name: chronos-sds-db
    shm_size: 128mb
    environment:
      POSTGRES_USER: sds-db-user
      POSTGRES_PASSWORD: sds-db-password
      POSTGRES_DB: chronos-schema-definition
    ports:
      - 5432:5432
    #    Activate for persistent local testdata:
    #    volumes:
    #      - ./data:/var/lib/postgresql/data
    #      - ./logs:/var/log/postgresql
    #      - ./certs:/var/lib/postgresql/certs
  
  chronos-ui:
    image: node:21.7.2-alpine3.18
    container_name: chronos-ui
    working_dir: /app
    command: npm start -- --host=0.0.0.0
    ports:
      - "4200:4200"
    volumes:
      - ./chronos-frontend:/app

  db-admin:
    image: adminer
    restart: always
    ports:
      - 7000:8080
