# SERVER
server.port=8090
# SECURITY
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${app.auth.issuer}/protocol/openid-connect/certs
app.auth.issuer=${APP_OAUTH_ISSUER}
app.auth.client-id=${APP_OAUTH_CLIENT_ID:chronos-admin-ui}
app.auth.principle-attribute=${APP_OAUTH_PRINCIPLE_ATTRIBUTE:preferred_username}
app.auth.admin-role=${APP_OAUTH_ADMIN_ROLE:chronos_client_schema-admin}
# PERSISTENCE
spring.datasource.url=jdbc:postgresql://chronos-schema-definition-db:5432/chronos-schema-definition
#TODO: Replace with Liquibase
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=<TODO>
spring.datasource.password=<TODO>
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
