spring.datasource.url=jdbc:postgresql://localhost:5432/sds-db
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=sds-db-user
spring.datasource.password=sds-db-password
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.show-sql=true
