# SERVER
server.port=8090
# SECURITY
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${app.auth.issuer}/protocol/openid-connect/certs
app.auth.issuer=${APP_OAUTH_ISSUER}
app.auth.client-id=${APP_OAUTH_CLIENT_ID:chronos-admin-ui}
app.auth.principle-attribute=${APP_OAUTH_PRINCIPLE_ATTRIBUTE:preferred_username}
app.auth.admin-role=${APP_OAUTH_ADMIN_ROLE:chronos_client_schema-admin}
# PERSISTENCE
spring.datasource.url=jdbc:postgresql://${APP_DB_HOST}:${APP_DB_PORT:5432}/${APP_DB_DATABASE:chronos-schema-definition}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${APP_DB_USER}
spring.datasource.password=${APP_DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/db.changelog-master.xml
