
@startuml architecture
  component "Keycloak" as IDP
  interface Auth

  frame Browser {
    component UI
  }

  frame "Cluster" {
    component "UI Server" as UIServer
    component UI
    component "UI Service" as UIS
    component "Gateway" as GW
    component "Schema Definition" as SDS
    component "Historical Data" as HDS
    component "Wiki Service" as Wiki
  }

  'Serve UI
  UI <.. UIServer

  'UI Access
  UI --> GW
  GW --> SDS : /api/schema
  GW --> HDS : /api/data
  GW --> Wiki : /api/wiki
  GW --> UIS : /api/ui

  'Cluster-internal Access
  HDS -> SDS : validation

  'Auth Integration
  IDP - Auth
  UI -left-> Auth
  HDS ---> Auth
  SDS ---> Auth
  Wiki ---> Auth


@enduml