POST http://localhost:8080/api/admin/entries
Content-Type: application/json

{
  "title": "Louis XVI"
}

###

GET http://localhost:8080/api/admin/entries

###

GET http://localhost:8080/api/admin/entries?ids=67,123,4

###

GET http://localhost:8080/api/admin/entries/4

###

PUT http://localhost:8080/api/admin/entries
Content-Type: application/json

{
  "id": 4,
  "title": "Charlemagne",
  "dateRanges": [
    {
      "type": "LIFE",
      "start": "0768-10-09",
      "end": "0814-01-28"
    }
  ],
  "tags": [
    {
      "id": 1
    },
    {
      "id": 2
    }
  ]
}

###

DELETE http://localhost:8080/api/admin/entries/2