# Get all (default: first 10 elements, no sorting)
GET http://localhost:8010/api/data

###

# Paging example)
GET http://localhost:8010/api/data?pageSize=5&page=2

### 

# Sorting example
GET http://localhost:8010/api/data?sortBy=from&sortAsc=false


###

# Statistics
GET http://localhost:8010/api/data/statistics

###

# By ID
GET http://localhost:8010/api/data/th