GET http://localhost:8090/api/schema

###

GET http://localhost:8090/api/schema/Territory



### ADMIN

### create

POST http://localhost:8090/api/schema/admin/entities
Content-Type: application/json

{
    "key": "Family",
    "attributes": [
        {
            "key": "name",
            "type": "STRING",
            "isArray": false,
            "valuePattern": "[a-zA-Z\\s]+"
        }
    ],
    "relations": [
      {
        "key": "FOUNDED_BY",
        "attributes": [
          {
            "key": "key1",
            "type": "STRING",
            "isArray": false
          },
          {
            "key": "key2",
            "type": "NUMBER",
            "isArray": false
          }
        ],
        "target": {
          "id": 2
        }
      }
    ]
}


### update

PUT http://localhost:8090/api/schema/admin/entities/Dynasty
Content-Type: application/json

{
  "id": 3,
  "key": "Dynasty",
  "explanation": "A family, important throughout a longer period, which a person belongs to",
  "examples": "Flavians (Roman Empire), Qing (China), Rockefellers (USA)",
  "attributes": [
    {
      "id": 3,
      "key": "name",
      "explanation": "The name of the dynasty",
      "examples": null,
      "type": "STRING",
      "isArray": false,
      "valuePattern": "[a-zA-Z\\s]+",
      "valueRange": null,
      "allowedValues": []
    },
    {
      "key": "type",
      "explanation": "Did the dynasty also include non-relatives",
      "examples": null,
      "type": "ENUM",
      "isArray": false,
      "valuePattern": null,
      "valueRange": null,
      "allowedValues": ["related-only", "adoptives", "all"]
    }
  ],
  "relations": []
}


### delete

DELETE http://localhost:8090/api/schema/admin/entities/Dynasty