### Default Language: English
GET http://localhost:8050/api/wiki/articles/Q1416

### Language: Italian
GET http://localhost:8050/api/wiki/articles/Q1416?lang=it



### ADMIN

### Search
GET http://localhost:8050/api/admin/wiki/articles/search?q=vitellius
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJyb2xlLXVzZXIiLCJyZXNvdXJjZV9hY2Nlc3MiOnsiY2hyb25vcy1hZG1pbi11aSI6eyJyb2xlcyI6WyJjaHJvbm9zX2NsaWVudF93aWtpLWFkbWluIl19fSwiaXNzIjoibG9jYWxob3N0IiwicHJlZmVycmVkX3VzZXJuYW1lIjoicm9sZS11c2VyIiwiZXhwIjo0OTI2MjU4MDM0LCJpYXQiOjE3NzI2NTgwMzR9.dgOpZ4r0_bVkJGucMtmTAA93FLBAVyBUp9Tli_li2YOCJkZKe-1OY8UKVHj0BGf4IBuyvwFuN3wBX3NDCWqIhqS-JiyQhSUlGkqbeco_dNERSIvSH84tKd-fwI-i6g_Q0jVoJubtBtIbaJDgc_sS2SUckEe4P0ZwgZA3UPkbmIm1qtfIUrNGSJGSK8rV1wd3y02Ap9vxz-6sCZqLFRdTeTZLkxQzdZiMw4434G9DrP4QTLZ9eXUEOe-KzpQ84_zRW6eDFLl-TfY6sbprhqbp1jlmFNoptar8xJ5IHg0F4J64WD6Y1MRO3QUyu5JaiLgf4c_7f5DeMrUXVC5Pc1SBaA

### Search: with language
GET http://localhost:8050/api/admin/wiki/articles/search?q=vitellius&lang=it
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJyb2xlLXVzZXIiLCJyZXNvdXJjZV9hY2Nlc3MiOnsiY2hyb25vcy1hZG1pbi11aSI6eyJyb2xlcyI6WyJjaHJvbm9zX2NsaWVudF93aWtpLWFkbWluIl19fSwiaXNzIjoibG9jYWxob3N0IiwicHJlZmVycmVkX3VzZXJuYW1lIjoicm9sZS11c2VyIiwiZXhwIjo0OTI2MjU4MDM0LCJpYXQiOjE3NzI2NTgwMzR9.dgOpZ4r0_bVkJGucMtmTAA93FLBAVyBUp9Tli_li2YOCJkZKe-1OY8UKVHj0BGf4IBuyvwFuN3wBX3NDCWqIhqS-JiyQhSUlGkqbeco_dNERSIvSH84tKd-fwI-i6g_Q0jVoJubtBtIbaJDgc_sS2SUckEe4P0ZwgZA3UPkbmIm1qtfIUrNGSJGSK8rV1wd3y02Ap9vxz-6sCZqLFRdTeTZLkxQzdZiMw4434G9DrP4QTLZ9eXUEOe-KzpQ84_zRW6eDFLl-TfY6sbprhqbp1jlmFNoptar8xJ5IHg0F4J64WD6Y1MRO3QUyu5JaiLgf4c_7f5DeMrUXVC5Pc1SBaA

